name: arcgis_mobility

channels:
  - esri
  - conda-forge

dependencies:
  - arcgis
  - black>=21
  - dask
  - h3-py>=4.1
  - isort
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - pandoc
  - pip
  - pytest
  - pyarrow
  - pyyaml
  - seaborn
  - shapely
  - swifter
  - tabulate
  - tqdm
  - pip:
    - autodocsumm
    - azure-storage-blob
    - boto3
    - build
    - bump2version
    - furo
    - ipykernel
    - nbsphinx
    - placekey
    - sphinx
    - sphinxcontrib-youtube
    - sphinx-autodoc-typehints
    - sphinx-copybutton
    - twine
